name: Maven CI/CD for Github Actions
on:
 push:
    branches: [ master ]
 pull_request:
    branches: [ master ]
    
env:
  AWS_DEFAULT_REGION: us-east-2
  AWS_DEFAULT_OUTPUT: json
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PRIMARY_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PRIMARY_SECRET_ACCESS_KEY }}

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14

    - name: Build project with Maven
      run: mvn -B -f pom.xml clean install

    - name: Build and tag the image
      run: |
        # Build and tag the image
        docker build -t "651827679494.dkr.ecr.us-east-2.amazonaws.com/actions:${{ github.run_number }}" .
        
    - name: Setup ECR
      run: |
        # Login to AWS ECR
        $( aws ecr get-login --no-include-email )
          
    - name: Publish Docker image
      run: docker push 651827679494.dkr.ecr.us-east-2.amazonaws.com/actions:${{ github.run_number }}

    - name: Trigger deploy
      uses: Consensys/kubernetes-action@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        IMAGE: ${{ secrets.DOCKER_REPO }}:${{ github.run_number }}
      with:
        args: set image deployment/myapp-deployment myapp-container=651827679494.dkr.ecr.us-east-2.amazonaws.com/actions:${{ github.run_number }} --record=true
      

   
