name: Maven CI/CD for Github Actions

on:
 push:
    branches: [ backup2 ]
 pull_request:
    branches: [ backup2 ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and tag the image
      run: |
        # Build and tag the image
        docker build -t ${{ secrets.DOCKER_REPO }}:${{ github.run_number }} .
        
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p "${{ secrets.DOCKER_PASSWORD }}"
        
    - name: Publish Docker image
      run: docker push ${{ secrets.DOCKER_REPO }}:${{ github.run_number }}

   
