name: Maven CI/CD

on:
 push:
    branches: [ master ]
 pull_request:
    branches: [ master ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14

    - name: Build project with Maven
      run: mvn -B -f pom.xml clean install

    - name: Build and tag the image
      run: |
        # Build and tag the image
        docker build -t ${{ secrets.DOCKER_REPO }}:latest .
        
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p "${{ secrets.DOCKER_PASSWORD }}"
        
    - name: Publish Docker image
      run: docker push ${{ secrets.DOCKER_REPO }}
      
    - name: Update deployment
      uses: ianbelcher/eks-kubectl-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_PRIMARY_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_PRIMARY_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_PRIMARY_REGION }}
        cluster_name: ${{ secrets.cluster_name }}
        args: set image --namespace default --record deployment/myapp-container myapp-container=${{ secrets.DOCKER_REPO }}:latest
